import helpers
import json
import logging

# file operation services


def get_json_data(filepath):
    try:
        file_text = open(filepath)
        return json.load(file_text)
    except Exception as exception:
        logging.error("Error occured while opening json source:{exception}"
                    .format(exception.__cause__))

        raise Exception("Error occured while opening json source:{exception}"
                      .format(exception.__cause__))


def get_txt_data():
    try:
        data = open(helpers.txt_file_path(), "r")
    except Exception as exception:
        logging.error("Error occured while opening json source:{exception}"
                    .format(exception.__cause__))

        raise Exception("Error occured while opening json source:{exception}"
                      .format(exception.__cause__))
    return data
